export enum EnvEnum {
  PORT = 'PORT',
  ENV = 'ENV',
  URL = 'URL',
  DATABASE_URL = 'DATABASE_URL',
  DATABASE_NAME = 'DATABASE_NAME',
  ORIGINS = 'ORIGINS',
  SENTRY_DSN = 'SENTRY_DSN',
  LOGGER = 'LOGGER',
  JWT_TOKEN = 'JWT_TOKEN',
  SALT_ROUND = 'SALT_ROUND'
}
